base:
- options/base/dataset/pretrain/SID_raw_gt.yaml        # train dataset
- options/base/dataset/test/SID_SonyA7S2_val_split.yaml  # test dataset
- options/DualPath/base/network_g/dual_path_unet.yaml  # network_g
- options/base/val_and_logger.yaml                     # val + logger

name: DualPath_Pretrain_Basic
model_type: DualPathModel
scale: 1
num_gpu: 1
manual_seed: 2022

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [200000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 200000
  warmup_iter: 5000  # warm up period

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  perceptual_opt:
    type: VGGPerceptualLoss
    layer_weights:
      conv1_2: 0.1
      conv2_2: 0.1
      conv3_4: 0.1
      conv4_4: 0.1
      conv5_4: 0.1
    vgg_type: vgg19
    loss_weight: 0.1

  gradient_opt:
    type: GradientLoss
    loss_weight: 0.5

path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

val:
  val_freq: !!float 2000
  save_img: true
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: false