base:
- options/base/dataset/pretrain/SID_train.yaml        # train dataset
- options/base/dataset/test/SID_SonyA7S2_val_split.yaml  # test dataset
- options/DualPath/base/network_g/dual_path_unet.yaml  # network_g
- options/base/noise_g/camera_params.yaml # camera_params
- options/base/val_and_logger.yaml                     # val + logger

name: DualPath_Pretrain_Basic
model_type: DualPathModel
scale: 1
num_gpu: 1
manual_seed: 2025

network_g:
  use_noise_map: true
  use_texture_detection: true

camera_name: SonyA7S2

# training settings
datasets:
  train:
    num_worker_per_gpu: 8
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [200000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  # TODO: test 5
  total_iter: 5
  warmup_iter: 5000  # warm up period

  # losses
  # 自适应纹理损失开关 (仅当use_texture_detection=true时生效)
  adaptive_loss: false

  # 损失函数设置
  # 当use_texture_detection=true且adaptive_loss=true时，会自动切换为AdaptiveTextureLoss
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
    # 以下参数仅当转换为AdaptiveTextureLoss时生效
    # pixel_loss_type: l1
    # flat_weight: 1.2        # 平坦区域权重
    # texture_weight: 1.0     # 纹理区域权重
    # perceptual_weight: 0.1  # 纹理区域感知损失权重
    # gradient_weight: 0.1    # 纹理区域梯度损失权重
    # texture_threshold: 0.5  # 纹理区域阈值
    # use_dynamic_weights: true # 使用动态权重

  # 常规感知损失设置
  perceptual_opt:
    type: VGGPerceptualLoss
    layer_weights:
      conv1_2: 0.1
      conv2_2: 0.1
      conv3_4: 0.1
      conv4_4: 0.1
      conv5_4: 0.1
    vgg_type: vgg19
    loss_weight: 0.1

  gradient_opt:
    type: GradientLoss
    loss_weight: 0.5

path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

val:
  val_freq: !!float 2
  save_img: true
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: false
  illumination_correct: true

  # logging settings
logger:
  print_freq: 2
  save_checkpoint_freq: !!float 5
  use_tb_logger: true
  wandb: ~