base:
- options/base/dataset/pretrain/SID_raw_gt.yaml
- options/base/dataset/test/SID_SonyA7S2_val_split.yaml
# - options/DualPath/base/network_g/dual_path_unet.yaml
- options/DualPath/base/network_g/dual_path_unet_e1.yaml  # network_g
- options/base/noise_g/noise_g_virtual.yaml
- options/base/val_and_logger.yaml

name: DualPath_Pretrain_Basic_restormer_e1_PMN_virtualNoise
model_type: DualPathModel
scale: 1
num_gpu: 1
manual_seed: 2025

network_g:
  use_noise_map: true
  use_texture_detection: true

# camera_name: SonyA7S2

# training settings
datasets:
  train:
    num_worker_per_gpu: 8
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    eta_min: !!float 1e-5
    periods: [100000, 100000, 100000]
    restart_weights: [1, 0.5, 0.25]

  total_iter: 300000
  warmup_iter: -1  # no warm up


  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  perceptual_opt:
    type: VGGPerceptualLoss
    layer_weights:
      conv1_2: 0.1
      conv2_2: 0.1
      conv3_4: 0.1
      conv4_4: 0.1
      conv5_4: 0.1
    vgg_type: vgg19
    loss_weight: 0.1

  gradient_opt:
    type: GradientLoss
    loss_weight: 0.5

path:
  pretrain_network_g: ~
  predefined_noise_g: ~
  strict_load_g: true
  resume_state: ~
  CRF: datasets/EMoR

val:
  val_freq: !!float 3000
  save_img: true
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: false
  illumination_correct: true

# logging settings
logger:
  print_freq: 300
  save_checkpoint_freq: !!float 3000
  use_tb_logger: true
  wandb: ~

use_amp: false
# accumulation_steps: 4