base:
- options/base/dataset/pretrain/SID_train.yaml                 # train dataset
- options/base/dataset/test/SID_SonyA7S2_val_split.yaml        # test dataset
- options/DualPath/base/network_g/dual_path_unet.yaml          # network_g
- options/DualPath/base/network_d/vgg_freq_disc.yaml           # network_d
- options/base/val_and_logger.yaml                             # val + logger

name: DualPath_GAN_Training
model_type: DualPathGANModel
scale: 1
num_gpu: 1
manual_seed: 2022

# training settings
datasets:
  train:
    num_worker_per_gpu: 8
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

train:
  optim_g:
    type: Adam
    lr: !!float 5e-5
    weight_decay: 0
    betas: [0.9, 0.999]

  optim_d:
    type: Adam
    lr: !!float 5e-5
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [150000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 150000
  warmup_iter: 2000

  # GAN
  net_d_iters: 1
  net_d_start_iter: 10000
  net_d_init_iters: 3

  # 对抗损失权重调度
  gan_weight_init: 0.0005
  gan_weight_final: 0.01
  gan_weight_start_iter: 10000
  gan_weight_end_iter: 80000

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  perceptual_opt:
    type: VGGPerceptualLoss
    layer_weights:
      conv3_4: 0.1
      conv4_4: 0.1
      conv5_4: 0.1
    vgg_type: vgg19
    loss_weight: 0.1

  gradient_opt:
    type: GradientLoss
    loss_weight: 0.5

  gan_opt:
    type: DualPathGANLoss
    gan_type: wgan_gp
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: 1.0       # 这是基础权重，实际权重会根据调度变化

path:
  pretrain_network_g: experiments/DualPath_Pretrain_Basic/models/net_g_latest.pth
  strict_load_g: true
  pretrain_network_d: ~
  strict_load_d: true
  resume_state: ~
  CRF: datasets/EMoR

val:
  val_freq: !!float 2000
  save_img: true
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: false
    # 可以考虑添加感知质量指标如LPIPS

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5000
  use_tb_logger: true
  wandb: ~